server:
  port: 10081
  
spring:
  application:
    name: pro-micro-series

eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/
      
  instance:
    hostname: localhost